config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/home', to: 'home#index'
  resources :items
  resources :storage_containers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/big_dependency.rb
class BigDependency
	def execute
		sleep(5)
	end

end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :storage_container
	validates :description, :name, presence: true

	def delete
		self.packed = false
	end

	def packed?
		self.packed
	end

	def mark_as_packed
		self.packed = true
	end

	def edit_name(new_name)
		self.name = new_name
	end

end

app/models/storage_container.rb
class StorageContainer < ApplicationRecord
  validates :name, presence: true
  has_many :items, dependent: :destroy
  accepts_nested_attributes_for :items, reject_if: :all_blank

  def empty?
  	items.empty?
  end

  def delete
    self.accessible = false if self.empty?
  end

  def add(item)
    items << item
  end

  def remove(item)
    items.delete(item)
  end

  def have_item?(item)
    items.include?(item)
  end

  def edit_name(name)
    self.name = name
  end

  def edit_description(description)
    self.description = description
  end
  
  def get_items
    items
  end

  def size
    items.size
  end

  def size
    items.size
  end

  def perform(big_dependency)
    big_dependency.execute
    return 42
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def index
    @items = if params[:term]
      Item.where('name LIKE ?', "%#{params[:term]}")
    else
      Item.all
    end
  end

  def create
		@items = Item.new(item_params)
    if @items.save
      redirect_to storage_containers_path
    end
	end

  def item_params
    params.require(:item).permit(:name, :term)
  end
end

app/controllers/storage_containers_controller.rb
class StorageContainersController < ApplicationController
	def new
		@storage_container = StorageContainer.new
    @storage_container.items << Item.new
	end

	def index
		@storage_containers = if params[:term]
      StorageContainer.where('name LIKE ?', "%#{params[:term]}")
    else
      StorageContainer.all
    end
	end

	def create
		@storage_container = StorageContainer.new(storage_container_params)
    if @storage_container.save
      redirect_to storage_containers_path
    else
      render :new
    end
	end

  def edit
    @storage_container = StorageContainer.find(params[:id])
  end

  def update
    @storage_container = StorageContainer.find(params[:id])
    @storage_container.update(storage_container_params)
    redirect_to storage_containers_path(@storage_container)
  end

  def destroy
    @storage_container = StorageContainer.find(params[:id])
    @storage_container.destroy
    redirect_to storage_containers_path
  end

  def storage_container_params
    params.require(:storage_container).permit(:name, :term, items_attributes: [:id, :name])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/storage_containers_helper.rb
module StorageContainersHelper
end

app/views/home/index.html.erb
<h1>Storage Organizer</h1>
<div class = "container">
	<div class = "content">
		<a href="http://localhost:3000/storage_containers" id="containers">Storage Containers</a>
		<a href="http://localhost:3000/items" id="items">Items</a>
	</div>
</div>

app/views/items/index.html.erb
<h1>All Items</h1>
<div class="container">
	<div class = "content">
	<%= form_tag(items_path, method: :get) do %>
		<%= text_field_tag(:term, params[:term], id: 'Search') %>
		<%= submit_tag('Search', name: nil, id: 'Submit') %>
	<% end %>
	</br>
	<table>
		<thead class="table_header">
			<tr>
				<th>Item Name</th>
				<th>Storage Container Name</th>
			</tr>
		</thead>
		<tbody>
			<% @items.each do |item| %>
			<tr class = "item row">
				<td><%= item.name%></td>
				<td><%= StorageContainer.find(item.storage_container_id).name %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
	<br />
	<br />
	<br />
	<br />
	<a href="http://localhost:3000/" id="storage_containers">Home</a>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StorageOrganizer</title>
	 <meta charset="utf-8" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/storage_containers/edit.html.erb
<h1>Edit Storage Container</h1>
<div class="container">
	<div class="content">
		<%= form_for @storage_container do |f| %>
			<%= f.label(:name) %>
			<%= f.text_field(:name) %>
			<%= f.fields_for :items do |ff|%>
				<%= ff.label(:name, "Items") %>
				<%= ff.text_field(:name, class: "item_name") %>
			<% end %>
			<br />
			<div id="item_list"></div>
			<button id="add_items" type="button" onclick="addItemField()">+</button>
			<br />
			<%= f.submit "Update Storage Container" %>
		<% end %>
		<br />
		<br />
		<br />
		<br />
		<a href="http://localhost:3000/storage_containers" id="storage_container">Go back</a>
	</div>
</div>

app/views/storage_containers/index.html.erb
<h1>Storage Containers</h1>
<div class="container">
<%= form_tag(storage_containers_path, method: :get) do %>
	<%= text_field_tag(:term, params[:term], id: 'Search') %>
	<%= submit_tag('Search', name: nil, id: 'Submit') %>
<% end %>
</br>
<table>
	<thead class="table_header">
		<tr>
			<th>Storage Container Name</th>
			<th>Number of Items</th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @storage_containers.each do |storage_container| %>
		<tr class="storage_container_row" onclick="toggleRow('<%= storage_container.id%>')">
			<td>
			<%= storage_container.name%>
			<table class="hidden_table" id="<%= storage_container.id%>">
				<thead><tr><th>Items</th></tr></thead>
				<tbody>
					<% storage_container.get_items.each do |item| %>
						<tr><td><%= item.name%></td></tr>
					<% end %>
				</tbody>
			</table>
			</td>
			<td><%= storage_container.size%></td>
			<td onclick="event.stopPropagation()"><%= button_to "Edit", edit_storage_container_path(storage_container), :method => :get %></td>
			<td onclick="event.stopPropagation()"><%= button_to "Delete", storage_container, :method => :delete %></td>
		</tr>
		<% end %>
	</tbody>
</table>
	<div class="content">
	<br />
	<br />
	<br />
	<a href="http://localhost:3000/" id="storage_containers">Home</a>
	<a href="http://localhost:3000/storage_containers/new" id="storage_containers">Add Another Container</a>
	</div>
</div>

app/views/storage_containers/new.html.erb
<h1>New Storage Container</h1>

<div class="container">
	<div class="content">
		<%= form_for(@storage_container) do |f| %>
			<div><%= f.label(:name) %></div>
			<%= f.text_field(:name) %>
			<br />
			Items:
			<div id="item_list"></div>
			<button id="add_items" type="button" onclick="addItemField()">+</button>
			<br />
			<%= f.submit "Create Storage Container" %>
		<% end %>
		<br />
		<br />
		<br />
		<br />
		<a href="http://localhost:3000/storage_containers" id="storage_container">Go back</a>
	</div>
</div>